# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20230627-035931-abstract-bar

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: fa

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer

- name: CRFEntityExtractor
- name: RegexEntityExtractor
  use_lookup_tables: True
  use_regexes: True

- name: DIETClassifier
  epoch: 200
  entity_recognition: False



# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
# - name: MemoizationPolicy
- name: RulePolicy

